### PR TITLE
Update cloudflare ip addresses

### PR DESCRIPTION
**Pull request by ErisDS**
The list has gotten out of date. Would be super useful if you could merge this and release an update.

### CODE REVIEW

**Comment by danneu** [comment]
@ErisDS Thanks, I'll push an update shortly.

**Comment by ErisDS** [comment]
Hi, could you please cut a release? Thanks.

**Comment by danneu** [comment]
@ErisDS Sorry, I should have done it before commenting.

I just published 0.0.7. https://www.npmjs.com/package/cloudflare-ip

**Comment by ErisDS** [comment]
Thanks 👍

**Pull request merged**
